[opencast]
# downloads_path = "test-downloads/"
downloads_path = "../../opencast/build/opencast-dist-develop-18-SNAPSHOT/data/opencast/downloads/"
#path_prefixes = ["/static"]


[jwt]
trusted_keys = [
    "https://explore.opencast.org/.well-known/jwks.json",
    "http://localhost:3080/.well-known/jwks.json",
]
#background_key_refresh = true
#key_cache_duration = "10min"


[http]
# on_allow = "empty"
on_allow = "file"
# on_allow = "x-accel-redirect:/protected"

# on_deny = "empty"
# on_deny = "x-accel-redirect:/static-opencast-fallback"

cors_allowed_origins = ["http://localhost:8030", "http://localhost:1234"]
address = "0.0.0.0"
#port =


[log]
filters.octoka = "trace"
