name: Create draft release and build release artifacts
on:
  push:
    tags:
    - 'v*.*'


# We have two separate jobs so that a human can start proof-reading and
# improving the release notes as quickly as possible. Generating the artifacts
# takes quite a while. This way, they are simply added once ready.
jobs:
  create-draft-release:
    name: Create draft release from tag
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true

  build-and-attach-artifacts:
    name: Build and attach release artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install musl requisites
        run: sudo apt install -y musl-dev musl-tools
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build release
        run: ./util/build-release.sh
      - name: create new release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/octoka
            deploy/config.toml
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true

  build-and-push-oci:
    name: Build and push OCI images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDX_PLATFORM: linux/amd64,linux/arm64
      DOCKER_BUILDX_OUTPUT: --push
    steps:
      - uses: actions/checkout@v6
      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.DOCKER_BUILDX_PLATFORM }}
      - name: docker info
        run: docker info
      - name: login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push OCI images
        run: ./util/build-oci.sh
